# Generated by Django 4.1 on 2023-05-10 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_new_datetime_alter_ram_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 19, 3, 54, 716857)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 19, 3, 54, 732484)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 10, 19, 3, 54, 716857)),
        ),
    ]
