# Generated by Django 4.1 on 2023-05-19 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_alter_new_datetime_alter_ram_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 34, 46, 68545)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 34, 46, 69566)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 34, 46, 67545)),
        ),
    ]
