# Generated by Django 4.2.1 on 2023-06-01 11:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_new_datetime_alter_ram_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bags',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('Backpack', 'Backpack'), ('Shoulder', 'Shoulder'), ('Sleeve', 'Sleeve'), ('Other', 'Other')], max_length=50)),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('Size', models.CharField(choices=[('13-14 inch', '13-14 inch'), ('15-16 inch', '15-16 inch'), ('17-18 inch', '17-18 inch')], max_length=50)),
                ('Cost', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Available', models.BooleanField(default=True)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 46, 55, 461719))),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(default='Unknown', max_length=50)),
                ('Condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('Type', models.CharField(choices=[('HDD', 'HDD'), ('SSD SATA 2.5', 'SSD SATA 2.5'), ('SSD M.2', 'SSD M.2'), ('SSD NVMe', 'SSD NVMe'), ('SSD PCIe', 'SSD PCIe')], max_length=20)),
                ('Size', models.IntegerField()),
                ('Speed', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('Cost', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Available', models.BooleanField(default=True)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 46, 55, 461719))),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='new',
            name='Cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='Cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ram',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='used',
            name='Cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 46, 55, 461719)),
        ),
        migrations.AlterField(
            model_name='new',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='HD_Type_Other',
            field=models.CharField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD')], default='HHD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 46, 55, 461719)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='Type',
            field=models.CharField(choices=[('DDR3', 'DDR3'), ('DDR3L', 'DDR3L'), ('DDR4', 'DDR4'), ('DDR5', 'DDR5')], max_length=20),
        ),
        migrations.AlterField(
            model_name='ram',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 46, 55, 461719)),
        ),
        migrations.AlterField(
            model_name='used',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='used',
            name='HD_Type_Other',
            field=models.CharField(blank=True, choices=[('SSD', 'SSD'), ('HDD', 'HDD')], default='HHD', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='used',
            name='Image',
            field=models.ImageField(upload_to='project/new/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='used',
            name='Model',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
