# Generated by Django 4.2.1 on 2023-06-01 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_bags_hard_new_cost_ram_cost_ram_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 47, 12, 206733)),
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 47, 12, 206733)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 47, 12, 206733)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 47, 12, 206733)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 47, 12, 206733)),
        ),
    ]
