# Generated by Django 4.2.1 on 2023-06-01 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_bags_datetime_alter_hard_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bags',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 54, 22, 299316)),
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 54, 22, 298319)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 54, 22, 297544)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 54, 22, 298319)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='Size',
            field=models.CharField(choices=[('4', '4'), ('8', '8'), ('16', '16'), ('32', '32'), ('64', '64')], max_length=100),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 14, 54, 22, 296313)),
        ),
    ]
