# Generated by Django 4.2.1 on 2023-06-01 13:07

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0028_alter_bags_datetime_alter_hard_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='bag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Brand', models.CharField(max_length=200)),
                ('Type', models.CharField(choices=[('Backpack', 'Backpack'), ('Shoulder', 'Shoulder'), ('Sleeve', 'Sleeve'), ('Other', 'Other')], max_length=50)),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)])),
                ('Size', models.CharField(choices=[('13-14 inch', '13-14 inch'), ('15-16 inch', '15-16 inch'), ('17-18 inch', '17-18 inch')], max_length=50)),
                ('Cost', models.IntegerField()),
                ('Price', models.IntegerField()),
                ('Available', models.BooleanField(default=True)),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 7, 42, 57904))),
                ('Description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='bags',
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 7, 42, 57904)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 7, 42, 57904)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 7, 42, 57904)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 7, 42, 57904)),
        ),
    ]
