# Generated by Django 4.2.1 on 2023-06-01 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0029_bag_delete_bags_alter_hard_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='images',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bag',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 33, 17, 967650)),
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 33, 17, 967650)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 33, 17, 967650)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 33, 17, 967650)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 16, 33, 17, 967650)),
        ),
    ]
