# Generated by Django 4.2.1 on 2023-06-10 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0031_alter_bag_datetime_alter_hard_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hard',
            name='Speed',
        ),
        migrations.AlterField(
            model_name='bag',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 4, 909555)),
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 4, 909555)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 4, 908555)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 4, 908555)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 10, 20, 43, 4, 907555)),
        ),
    ]
