# Generated by Django 4.2.1 on 2023-08-08 20:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0032_remove_hard_speed_alter_bag_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 3, 14, 755355)),
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 3, 14, 755355)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 3, 14, 754355)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 3, 14, 754355)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 8, 22, 3, 14, 753305)),
        ),
    ]
