# Generated by Django 4.2.4 on 2023-08-14 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0033_alter_bag_datetime_alter_hard_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 19, 26, 53, 421292)),
        ),
        migrations.AlterField(
            model_name='hard',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 19, 26, 53, 421292)),
        ),
        migrations.AlterField(
            model_name='new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 19, 26, 53, 420295)),
        ),
        migrations.AlterField(
            model_name='ram',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 19, 26, 53, 420295)),
        ),
        migrations.AlterField(
            model_name='used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 14, 19, 26, 53, 419298)),
        ),
    ]
