# Generated by Django 4.1 on 2023-05-10 15:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice_used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Ram', models.IntegerField()),
                ('Hard Disk', models.CharField(max_length=50)),
                ('Second Hard Disk', models.CharField(blank=True, max_length=50, null=True)),
                ('S/N', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField()),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 54, 59, 280446))),
                ('Product_id', models.ManyToManyField(to='products.used')),
            ],
        ),
        migrations.CreateModel(
            name='invoice_new',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Ram', models.IntegerField()),
                ('Hard Disk', models.CharField(max_length=50)),
                ('Second Hard Disk', models.CharField(blank=True, max_length=50, null=True)),
                ('S/N', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField()),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 5, 10, 18, 54, 59, 280446))),
                ('Product_id', models.ManyToManyField(to='products.new')),
            ],
        ),
    ]
