# Generated by Django 4.1 on 2023-05-11 13:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_new_datetime_alter_ram_datetime_and_more'),
        ('management', '0013_alter_invoice_new_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_new',
            old_name='Hard Disk',
            new_name='HardDisk',
        ),
        migrations.RenameField(
            model_name='invoice_new',
            old_name='S/N',
            new_name='HardDisk_Other',
        ),
        migrations.RenameField(
            model_name='invoice_new',
            old_name='Second Hard Disk',
            new_name='SN',
        ),
        migrations.AlterField(
            model_name='invoice_new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 11, 16, 25, 50, 101863)),
        ),
        migrations.CreateModel(
            name='invoice_used',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Phone', models.IntegerField()),
                ('Quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('Ram', models.IntegerField()),
                ('Hard Disk', models.CharField(max_length=50)),
                ('Second Hard Disk', models.CharField(blank=True, max_length=50, null=True)),
                ('S/N', models.CharField(blank=True, max_length=50, null=True)),
                ('Price', models.IntegerField()),
                ('DateTime', models.DateTimeField(default=datetime.datetime(2023, 5, 11, 16, 25, 50, 101863))),
                ('Product_id', models.ManyToManyField(to='products.used')),
            ],
        ),
    ]
