# Generated by Django 4.1 on 2023-05-15 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0016_alter_invoice_new_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_new',
            name='Branch',
            field=models.CharField(default=12, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice_used',
            name='Branch',
            field=models.CharField(default='fww', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 15, 56, 48, 563806)),
        ),
        migrations.AlterField(
            model_name='invoice_used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 15, 15, 56, 48, 563806)),
        ),
    ]
