# Generated by Django 4.1 on 2023-05-16 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0018_alter_invoice_new_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice_new',
            name='Branch',
        ),
        migrations.AlterField(
            model_name='invoice_new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 13, 18, 15, 279205)),
        ),
        migrations.AlterField(
            model_name='invoice_used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 13, 18, 15, 279205)),
        ),
    ]
