# Generated by Django 4.1 on 2023-05-19 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0020_alter_invoice_new_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice_new',
            name='Branch',
            field=models.CharField(choices=[('Computer Souq', 'Computer Souq'), ('Carnival', 'Carnival'), ('Sajed', 'Sajed'), ('Carnival', 'Carnival')], default='ews', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice_new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 34, 46, 75547)),
        ),
        migrations.AlterField(
            model_name='invoice_used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 16, 34, 46, 77551)),
        ),
    ]
