# Generated by Django 4.1 on 2023-05-19 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_alter_new_datetime_alter_ram_datetime_and_more'),
        ('management', '0023_alter_invoice_new_datetime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice_used',
            old_name='Hard Disk',
            new_name='HardDisk',
        ),
        migrations.RenameField(
            model_name='invoice_used',
            old_name='S/N',
            new_name='HardDisk_Other',
        ),
        migrations.RenameField(
            model_name='invoice_used',
            old_name='Second Hard Disk',
            new_name='SN',
        ),
        migrations.AlterField(
            model_name='invoice_new',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 55, 44, 121019)),
        ),
        migrations.AlterField(
            model_name='invoice_used',
            name='Branch',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='invoice_used',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 22, 55, 44, 121019)),
        ),
        migrations.AlterField(
            model_name='invoice_used',
            name='Product_id',
            field=models.ManyToManyField(to='products.new'),
        ),
    ]
